# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=1000)),
                ('source', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(verbose_name='date published')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reference',
            name='reference_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ReferenceList'),
        ),
    ]
